version: '2'
services:
  web:
    build: .
    links:
      - mongo:mongo
      - redis:redis
    ports:
      - "80:3000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:3.0.12
    volumes:
      - ./data/mongo:/data/db
    command: --smallfiles
  redis:
    image: redis:3.0.7
    volumes:
      - ./data/redis:/data
